/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Koala;

import client.Client;
import javax.swing.JOptionPane;
import utils.Status;

/**
 *
 * @author Kam
 */
public class MainFrame extends javax.swing.JFrame {

    private Client program; //logika
    private String login; //login usera
    private String pass; //haslo
    private String userId; //numer uzytkownika
    public Contacts_List list; //lista kontaktow

    public MainFrame(Client klient, String tempLogin, String tempPassword) {
        this.program = klient;
        this.login = tempLogin;
        this.pass = tempPassword;
        new Listener(this).start();
        new GetStatusThread(this).start();
        new ServerListener(this).start();
        initComponents();
        list = new Contacts_List(this.program, this.panel, this);
        panel.setSize(500, 550);
        try {
            program.getId();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        this.myLabel.setText("Tutaj będzie numer");
    }

    public String getId() {
        return this.myLabel.getText();
    }
    
    public void setId(String temp) {
        this.userId = temp;
    }

    public void showMessage(String pmMessage) {
        JOptionPane.showMessageDialog(null, pmMessage);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        logoutButton = new javax.swing.JButton();
        statusComoBox = new javax.swing.JComboBox();
        panel = new javax.swing.JPanel();
        myLabel = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        exitMenuItem = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        importMenuItem = new javax.swing.JMenuItem();
        exportMenuItem = new javax.swing.JMenuItem();
        addContactMenuItem = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        logoutButton.setText("Wyloguj");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        statusComoBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Dostępny", "Niewidoczny" }));
        statusComoBox.setSelectedIndex(1);
        statusComoBox.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        statusComoBox.setName("status"); // NOI18N
        statusComoBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusComoBoxActionPerformed(evt);
            }
        });

        panel.setBackground(new java.awt.Color(0, 204, 204));

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 261, Short.MAX_VALUE)
        );

        myLabel.setText("Numer:");

        jMenu1.setText("Menu");

        exitMenuItem.setText("Wyjdź");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(exitMenuItem);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Kontakty");

        importMenuItem.setText("Import kontaktów");
        jMenu3.add(importMenuItem);

        exportMenuItem.setText("Eksport kontaktów");
        jMenu3.add(exportMenuItem);

        addContactMenuItem.setText("Dodaj Kontakt");
        addContactMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addContactMenuItemActionPerformed(evt);
            }
        });
        jMenu3.add(addContactMenuItem);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(statusComoBox, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(myLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logoutButton)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(statusComoBox)
                    .addComponent(myLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        statusComoBox.getAccessibleContext().setAccessibleName("status");
        statusComoBox.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        try {
            program.logoutFromServer();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        System.exit(0);
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
            program.logoutFromServer();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_formWindowClosing

    private void statusComoBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusComoBoxActionPerformed
        try {
            if (program.getCzyZalgowany()) {
                if (statusComoBox.getSelectedIndex() == 1) {
                    program.changeStatus(Status.INVISIBLE);
                } else if (statusComoBox.getSelectedIndex() == 0) {
                    program.changeStatus(Status.AVALIBLE);
                }
            } else {
                System.out.println("Wylogowany!!!");
            }
        } catch (Exception e) {
            System.out.println("229");
        }
    }//GEN-LAST:event_statusComoBoxActionPerformed

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        try {
            program.logoutFromServer();
            System.exit(0);
        } catch (Exception e) {
            System.out.println("linijka 211, MainFrame");
        }
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void addContactMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addContactMenuItemActionPerformed
        new Add(null, list, false).setVisible(true);
    }//GEN-LAST:event_addContactMenuItemActionPerformed
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addContactMenuItem;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenuItem exportMenuItem;
    private javax.swing.JMenuItem importMenuItem;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JButton logoutButton;
    private javax.swing.JLabel myLabel;
    private javax.swing.JPanel panel;
    private javax.swing.JComboBox statusComoBox;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the program
     */
    public Client getProgram() {
        return program;
    }

    /**
     * @return the login
     */
    public String getLogin() {
        return login;
    }

    /**
     * @return the pass
     */
    public String getPass() {
        return pass;
    }

    /**
     * @return the userId
     */
    public String getUserId() {
        return userId;
    }

    /**
     * @param userId the userId to set
     */
    public void setUserId(String mId) {
        this.userId = mId;
    }
}
